### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by GZY2000** [albrateanu/LYT-Net#13]
您好，我想问一下是在yuv颜色空间进行训练测试的嘛？

**Comment by albrateanu** [comment]
Hello. Training and testing are both done on RGB. 
The model just converts an RGB input to YUV before the forward pass. But images are loaded as RGB, both for training and validation.
Please see TensorFlow version for a more accurate depiction. PyTorch version currently still has some issues with YUV.

**Comment by GZY2000** [comment]
> Hello. Training and testing are both done on RGB. The model just converts an RGB input to YUV before the forward pass. But images are loaded as RGB, both for training and validation. Please see TensorFlow version for a more accurate depiction. PyTorch version currently still has some issues with YUV.

谢谢您的回复，因为我看到tensorflow版本中，读取的是rgb图像，在前向传递之前进行了yuv转换，后续并未转换为rgb，是网络在返回的过程中自动返回为rgb了吗？这个点我没太理解，期待您的回复！

**Comment by stuhao251** [comment]
他这个权重生成增强后的图片，用哪个文件啊，这个没有test.py文件

**Comment by albrateanu** [comment]
@GZY2000 The idea behind the YUV conversion is that it represents a formula-based decomposition between color information (U and V) and illumination information (Y). As such, we treat the YUV decomposition like you would treat a Retinex decomposition - but a Retinex decomposition requires a separate network that learns the decomposition, whereas YUV is formula based. So we don't convert back to RGB explicitly, because we process the features in the network in a manner that treats Y as L and (U,V) as R, where R and L are reflectance and luminance in the Retinex model.
@stuhao251 Will be adding a test.py file in short time. Results were originally generated with TensorFlow version.

**Comment by GZY2000** [comment]
> @GZY2000 The idea behind the YUV conversion is that it represents a formula-based decomposition between color information (U and V) and illumination information (Y). As such, we treat the YUV decomposition like you would treat a Retinex decomposition - but a Retinex decomposition requires a separate network that learns the decomposition, whereas YUV is formula based. So we don't convert back to RGB explicitly, because we process the features in the network in a manner that treats Y as L and (U,V) as R, where R and L are reflectance and luminance in the Retinex model. @stuhao251 Will be adding a test.py file in short time. Results were originally generated with TensorFlow version.

好的，非常感谢您的回复，祝您科研顺利！
