### ISSUE TITLE
About training parameter configuration

### ISSUE THREAD

**Issue by AlanFool-1** [albrateanu/LYT-Net#2]
Are the training parameter configurations of the three data sets the same? I can only get 22dB PSNR on LOL-v1 dataset.

**Comment by albrateanu** [comment]
Hello. Thanks for your message.

The pre-trained weights are available for all datasets in the ```pretrained_weights``` folder.

We will provide training logs to be downloaded in the upcoming weeks.

The main differences stem from iterations, as the mentioned number is more of an orientation rather than an exact number. Datasets have different sizes so iterations required are different.

There was also an issue with certain randomness not being accounted for during development. Randomness of generated image patches and weight initializations to be more specific. It is an issue to solve.
